// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Details: typeof import('./src/components/musicitem/details.vue')['default']
    FooterMusic: typeof import('./src/components/musicitem/footerMusic.vue')['default']
    IconList: typeof import('./src/components/home/iconList.vue')['default']
    'Item.Bottom': typeof import('./src/components/musicitem/item.Bottom.vue')['default']
    ItemTop: typeof import('./src/components/musicitem/itemTop.vue')['default']
    MusicList: typeof import('./src/components/home/musicList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/home/swiper.vue')['default']
    TopNav: typeof import('./src/components/home/topNav.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
